const TCategorie = [
  "Cardiology",
  "Dermatology",
  "Endocrinology",
  "Gastroenterology",
  "Hematology",
  "Infectious Diseases",
  "Nephrology",
  "Neurology",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Otolaryngology",
  "Pediatrics",
  "Psychiatry",
  "Pulmonology",
  "Rheumatology",
  "Surgery",
  "Urology",
  "Gynecology",
  "Allergy and Immunology",
  "Anesthesiology",
  "Emergency Medicine",
  "Family Medicine",
  "Geriatrics",
  "Palliative Care",
  "Plastic Surgery",
  "Radiology",
  "Sports Medicine",
  "General Medicine",
  "Preventive Medicine",
  "Genetics",
  "Occupational Medicine",
  "Physical Medicine and Rehabilitation",
  "Sleep Medicine",
  "Transplant Medicine",
  "Pain Management",
  "Vascular Surgery",
  "Thoracic Surgery",
  "Clinical Pharmacology",
  "Medical Toxicology",
  "Nuclear Medicine",
  "Hyperbaric Medicine",
  "Critical Care Medicine",
  "Addiction Medicine",
  "Adolescent Medicine",
  "Maternal-Fetal Medicine",
  "Neonatology",
  "Reproductive Endocrinology",
  "Hospice and Palliative Medicine",
  "Teeth Orthodontics",
  "Cosmetic Dentistry",
  "Cavity Protection",
  "Oral Surgery",
  "Pediatric Dental",
];
module.exports = {
  TCategorie,
};
